version: "3"
services:
  graphql:
    build: .
    image: graphql
    container_name: graphql
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
