service:
  name: tdr-graphql

# Add the serverless-webpack plugin
plugins:
  - serverless-offline-ssm
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  role: arn:aws:iam::247222723249:role/lambda-vpc-role

functions:
  tdr:
    handler: src/handler.tdr
    events:
      - http:
          method: post
          path: graphql
          cors: true
          authorizer:aws sam.
            arn: arn:aws:cognito-idp:eu-west-2:247222723249:userpool/eu-west-2_6Mn0M2i9C
    environment:
      REACT_APP_MYSQL_HOST: 127.0.0.1
      REACT_APP_MYSQL_USER: root
      REACT_APP_MYSQL_PASSWORD: password
    vpc:
      securityGroupIds:
        - sg-c24e48a8
      subnetIds:
        - subnet-8bc567f1
        - subnet-866701ef
        - subnet-d024d59c
