service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  tdr:
    handler: src/handler.tdr
    events:
      - http:
          method: post
          path: graphql
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:247222723249:userpool/eu-west-2_6Mn0M2i9C
    environment:
      GRAPHQL_SERVER: ${ssm:graphqlserver}
      MYSQL_HOST: ${ssm:mysqlhost}
      MYSQL_USER: ${ssm:mysqluser}
      MYSQL_PASSWORD: ${ssm:mysqlpassword}
